Added mandatory "device" path to volumes example
By using the example provided, the following error will show up:
Creating volume "architecture_grakndata" with local driver
ERROR: create architecture_grakndata: missing required option: "device"

To resolve this issue, it simply needs to add the mandatory "device" option.